// <auto-generated />
namespace TeamGit.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class meow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(meow));
        
        string IMigrationMetadata.Id
        {
            get { return "202103021839506_meow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
