// <auto-generated />
namespace TeamGit.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class teamgit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teamgit));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020309279_teamgit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
